//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE_SchlumbergerWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arth_hotels
    {
        public string address { get; set; }
        public string categories { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string name { get; set; }
        public string postalCode { get; set; }
        public string province { get; set; }
        public string reviews_rating { get; set; }
        public string reviews_text { get; set; }
        public string reviews_title { get; set; }
        public string reviews_username { get; set; }
        public int id { get; set; }
    }
}
